# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/forms/break_screen.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWidget(object):
    def setupUi(self, mainWidget):
        mainWidget.setObjectName("mainWidget")
        mainWidget.resize(732, 532)
        icon = QtGui.QIcon.fromTheme("koffeebreak")
        mainWidget.setWindowIcon(icon)
        mainWidget.setAutoFillBackground(False)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(mainWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(mainWidget)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("#widget{\n"
"    background-color: rgb(0,0,0,127);\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(108, 14, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.mainFrame = QtWidgets.QFrame(self.widget)
        self.mainFrame.setStyleSheet("#mainFrame{\n"
"    background-color: #3daee9;\n"
"padding: -5px;\n"
"}")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setLineWidth(0)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mainWidget = QtWidgets.QWidget(self.mainFrame)
        self.mainWidget.setMouseTracking(False)
        self.mainWidget.setAutoFillBackground(True)
        self.mainWidget.setStyleSheet("#mainFrame {\n"
"    border-width: 3px;\n"
"    border-color: #3daee9;\n"
"    /*border-style: solid;*/\n"
"    /*background-color: #EFF0F1;*/\n"
"}")
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout_5.setContentsMargins(20, 5, 20, 20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.mainWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.icon_label = QtWidgets.QLabel(self.mainWidget)
        self.icon_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.icon_label.setAutoFillBackground(True)
        self.icon_label.setStyleSheet("")
        self.icon_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.icon_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.icon_label.setLineWidth(1)
        self.icon_label.setText("")
        self.icon_label.setScaledContents(False)
        self.icon_label.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_label.setWordWrap(False)
        self.icon_label.setIndent(0)
        self.icon_label.setObjectName("icon_label")
        self.verticalLayout_2.addWidget(self.icon_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 15)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.mainWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(True)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.leftTime_label = QtWidgets.QLabel(self.mainWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.leftTime_label.setFont(font)
        self.leftTime_label.setAutoFillBackground(True)
        self.leftTime_label.setStyleSheet("")
        self.leftTime_label.setTextFormat(QtCore.Qt.PlainText)
        self.leftTime_label.setObjectName("leftTime_label")
        self.horizontalLayout_3.addWidget(self.leftTime_label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.setStretch(0, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.mainWidget)
        self.line.setWindowModality(QtCore.Qt.NonModal)
        self.line.setAutoFillBackground(True)
        self.line.setStyleSheet("")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(3)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 20, -1, 20)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lockScreen_pushButton = QtWidgets.QPushButton(self.mainWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(False)
        font.setKerning(True)
        self.lockScreen_pushButton.setFont(font)
        self.lockScreen_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lockScreen_pushButton.setAutoFillBackground(True)
        self.lockScreen_pushButton.setStyleSheet("")
        self.lockScreen_pushButton.setIconSize(QtCore.QSize(16, 16))
        self.lockScreen_pushButton.setDefault(True)
        self.lockScreen_pushButton.setFlat(False)
        self.lockScreen_pushButton.setObjectName("lockScreen_pushButton")
        self.verticalLayout.addWidget(self.lockScreen_pushButton)
        self.breakComp_pushButton = QtWidgets.QPushButton(self.mainWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(False)
        font.setKerning(True)
        self.breakComp_pushButton.setFont(font)
        self.breakComp_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.breakComp_pushButton.setAutoFillBackground(True)
        self.breakComp_pushButton.setStyleSheet("")
        self.breakComp_pushButton.setIconSize(QtCore.QSize(16, 16))
        self.breakComp_pushButton.setFlat(False)
        self.breakComp_pushButton.setObjectName("breakComp_pushButton")
        self.verticalLayout.addWidget(self.breakComp_pushButton)
        self.postponeBreak_pushButton = QtWidgets.QPushButton(self.mainWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(False)
        font.setKerning(True)
        self.postponeBreak_pushButton.setFont(font)
        self.postponeBreak_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.postponeBreak_pushButton.setAutoFillBackground(True)
        self.postponeBreak_pushButton.setStyleSheet("")
        self.postponeBreak_pushButton.setIconSize(QtCore.QSize(16, 16))
        self.postponeBreak_pushButton.setFlat(False)
        self.postponeBreak_pushButton.setObjectName("postponeBreak_pushButton")
        self.verticalLayout.addWidget(self.postponeBreak_pushButton)
        self.skipBreak_pushButton = QtWidgets.QPushButton(self.mainWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(False)
        font.setKerning(True)
        self.skipBreak_pushButton.setFont(font)
        self.skipBreak_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.skipBreak_pushButton.setAutoFillBackground(True)
        self.skipBreak_pushButton.setStyleSheet("")
        self.skipBreak_pushButton.setIconSize(QtCore.QSize(16, 16))
        self.skipBreak_pushButton.setFlat(False)
        self.skipBreak_pushButton.setObjectName("skipBreak_pushButton")
        self.verticalLayout.addWidget(self.skipBreak_pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.mainWidget)
        self.verticalLayout_3.addWidget(self.mainFrame)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(107, 14, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.horizontalLayout_2.addWidget(self.widget)

        self.retranslateUi(mainWidget)
        QtCore.QMetaObject.connectSlotsByName(mainWidget)

    def retranslateUi(self, mainWidget):
        _translate = QtCore.QCoreApplication.translate
        mainWidget.setWindowTitle(_translate("mainWidget", "KoffeeBreak - Lockscreen"))
        self.label_2.setText(_translate("mainWidget", "How about a cup of coffee?"))
        self.label_3.setText(_translate("mainWidget", "Left: "))
        self.leftTime_label.setText(_translate("mainWidget", "00:00"))
        self.lockScreen_pushButton.setText(_translate("mainWidget", "Lock screen"))
        self.breakComp_pushButton.setText(_translate("mainWidget", "Break at the computer"))
        self.postponeBreak_pushButton.setText(_translate("mainWidget", "Postpone break"))
        self.skipBreak_pushButton.setText(_translate("mainWidget", "Skip the break"))

