# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/forms/main.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(677, 388)
        icon = QtGui.QIcon.fromTheme("koffeebreak")
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setLineWidth(1)
        self.label.setMidLineWidth(0)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.allTime_lbl = QtWidgets.QLabel(self.groupBox)
        self.allTime_lbl.setLineWidth(1)
        self.allTime_lbl.setMidLineWidth(0)
        self.allTime_lbl.setScaledContents(False)
        self.allTime_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allTime_lbl.setObjectName("allTime_lbl")
        self.horizontalLayout.addWidget(self.allTime_lbl)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setLineWidth(1)
        self.label_3.setMidLineWidth(0)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.workTime_lbl = QtWidgets.QLabel(self.groupBox)
        self.workTime_lbl.setLineWidth(1)
        self.workTime_lbl.setMidLineWidth(0)
        self.workTime_lbl.setScaledContents(False)
        self.workTime_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.workTime_lbl.setObjectName("workTime_lbl")
        self.horizontalLayout_2.addWidget(self.workTime_lbl)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setLineWidth(1)
        self.label_5.setMidLineWidth(0)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.shortBreakTime_lbl = QtWidgets.QLabel(self.groupBox)
        self.shortBreakTime_lbl.setLineWidth(1)
        self.shortBreakTime_lbl.setMidLineWidth(0)
        self.shortBreakTime_lbl.setScaledContents(False)
        self.shortBreakTime_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shortBreakTime_lbl.setObjectName("shortBreakTime_lbl")
        self.horizontalLayout_3.addWidget(self.shortBreakTime_lbl)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setLineWidth(1)
        self.label_7.setMidLineWidth(0)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.longBreakTime_lbl = QtWidgets.QLabel(self.groupBox)
        self.longBreakTime_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.longBreakTime_lbl.setAutoFillBackground(False)
        self.longBreakTime_lbl.setFrameShadow(QtWidgets.QFrame.Plain)
        self.longBreakTime_lbl.setLineWidth(1)
        self.longBreakTime_lbl.setMidLineWidth(0)
        self.longBreakTime_lbl.setScaledContents(False)
        self.longBreakTime_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.longBreakTime_lbl.setObjectName("longBreakTime_lbl")
        self.horizontalLayout_4.addWidget(self.longBreakTime_lbl)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox1.setAutoFillBackground(True)
        self.groupBox1.setObjectName("groupBox1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox1)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.groupBox1)
        self.label_11.setLineWidth(1)
        self.label_11.setMidLineWidth(0)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.numberOfShortBreak_lbl = QtWidgets.QLabel(self.groupBox1)
        self.numberOfShortBreak_lbl.setLineWidth(1)
        self.numberOfShortBreak_lbl.setMidLineWidth(0)
        self.numberOfShortBreak_lbl.setScaledContents(False)
        self.numberOfShortBreak_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numberOfShortBreak_lbl.setObjectName("numberOfShortBreak_lbl")
        self.horizontalLayout_6.addWidget(self.numberOfShortBreak_lbl)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.groupBox1)
        self.label_9.setLineWidth(1)
        self.label_9.setMidLineWidth(0)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.numberOfShortBreakComp_lbl = QtWidgets.QLabel(self.groupBox1)
        self.numberOfShortBreakComp_lbl.setLineWidth(1)
        self.numberOfShortBreakComp_lbl.setMidLineWidth(0)
        self.numberOfShortBreakComp_lbl.setScaledContents(False)
        self.numberOfShortBreakComp_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numberOfShortBreakComp_lbl.setObjectName("numberOfShortBreakComp_lbl")
        self.horizontalLayout_5.addWidget(self.numberOfShortBreakComp_lbl)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.groupBox1)
        self.label_13.setLineWidth(1)
        self.label_13.setMidLineWidth(0)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.numberOfPostponedShortBreaks_lbl = QtWidgets.QLabel(self.groupBox1)
        self.numberOfPostponedShortBreaks_lbl.setLineWidth(1)
        self.numberOfPostponedShortBreaks_lbl.setMidLineWidth(0)
        self.numberOfPostponedShortBreaks_lbl.setScaledContents(False)
        self.numberOfPostponedShortBreaks_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numberOfPostponedShortBreaks_lbl.setObjectName("numberOfPostponedShortBreaks_lbl")
        self.horizontalLayout_7.addWidget(self.numberOfPostponedShortBreaks_lbl)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_15 = QtWidgets.QLabel(self.groupBox1)
        self.label_15.setLineWidth(1)
        self.label_15.setMidLineWidth(0)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.numberOfSkippededShortBreaks_lbl = QtWidgets.QLabel(self.groupBox1)
        self.numberOfSkippededShortBreaks_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.numberOfSkippededShortBreaks_lbl.setAutoFillBackground(False)
        self.numberOfSkippededShortBreaks_lbl.setFrameShadow(QtWidgets.QFrame.Plain)
        self.numberOfSkippededShortBreaks_lbl.setLineWidth(1)
        self.numberOfSkippededShortBreaks_lbl.setMidLineWidth(0)
        self.numberOfSkippededShortBreaks_lbl.setScaledContents(False)
        self.numberOfSkippededShortBreaks_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numberOfSkippededShortBreaks_lbl.setObjectName("numberOfSkippededShortBreaks_lbl")
        self.horizontalLayout_8.addWidget(self.numberOfSkippededShortBreaks_lbl)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_13.addWidget(self.groupBox1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setLineWidth(1)
        self.label_19.setMidLineWidth(0)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_10.addWidget(self.label_19)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.numberOfLongBreak_lbl = QtWidgets.QLabel(self.groupBox_2)
        self.numberOfLongBreak_lbl.setLineWidth(1)
        self.numberOfLongBreak_lbl.setMidLineWidth(0)
        self.numberOfLongBreak_lbl.setScaledContents(False)
        self.numberOfLongBreak_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numberOfLongBreak_lbl.setObjectName("numberOfLongBreak_lbl")
        self.horizontalLayout_10.addWidget(self.numberOfLongBreak_lbl)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setLineWidth(1)
        self.label_17.setMidLineWidth(0)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_9.addWidget(self.label_17)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.numberOfLongBreakComp_lbl = QtWidgets.QLabel(self.groupBox_2)
        self.numberOfLongBreakComp_lbl.setLineWidth(1)
        self.numberOfLongBreakComp_lbl.setMidLineWidth(0)
        self.numberOfLongBreakComp_lbl.setScaledContents(False)
        self.numberOfLongBreakComp_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numberOfLongBreakComp_lbl.setObjectName("numberOfLongBreakComp_lbl")
        self.horizontalLayout_9.addWidget(self.numberOfLongBreakComp_lbl)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setLineWidth(1)
        self.label_21.setMidLineWidth(0)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_11.addWidget(self.label_21)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.numberOfPostponedLongBreaks_lbl = QtWidgets.QLabel(self.groupBox_2)
        self.numberOfPostponedLongBreaks_lbl.setLineWidth(1)
        self.numberOfPostponedLongBreaks_lbl.setMidLineWidth(0)
        self.numberOfPostponedLongBreaks_lbl.setScaledContents(False)
        self.numberOfPostponedLongBreaks_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numberOfPostponedLongBreaks_lbl.setObjectName("numberOfPostponedLongBreaks_lbl")
        self.horizontalLayout_11.addWidget(self.numberOfPostponedLongBreaks_lbl)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setLineWidth(1)
        self.label_23.setMidLineWidth(0)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_12.addWidget(self.label_23)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem11)
        self.numberOfSkippededLongBreaks_lbl = QtWidgets.QLabel(self.groupBox_2)
        self.numberOfSkippededLongBreaks_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.numberOfSkippededLongBreaks_lbl.setAutoFillBackground(False)
        self.numberOfSkippededLongBreaks_lbl.setFrameShadow(QtWidgets.QFrame.Plain)
        self.numberOfSkippededLongBreaks_lbl.setLineWidth(1)
        self.numberOfSkippededLongBreaks_lbl.setMidLineWidth(0)
        self.numberOfSkippededLongBreaks_lbl.setScaledContents(False)
        self.numberOfSkippededLongBreaks_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numberOfSkippededLongBreaks_lbl.setObjectName("numberOfSkippededLongBreaks_lbl")
        self.horizontalLayout_12.addWidget(self.numberOfSkippededLongBreaks_lbl)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13.addWidget(self.groupBox_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.reset_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.reset_pushButton.setObjectName("reset_pushButton")
        self.horizontalLayout_14.addWidget(self.reset_pushButton)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem12)
        self.close_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.close_pushButton.setDefault(True)
        self.close_pushButton.setObjectName("close_pushButton")
        self.horizontalLayout_14.addWidget(self.close_pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 677, 30))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "KoffeeBreak"))
        self.groupBox.setTitle(_translate("mainWindow", "Time"))
        self.label.setText(_translate("mainWindow", "All time"))
        self.allTime_lbl.setText(_translate("mainWindow", "0"))
        self.label_3.setText(_translate("mainWindow", "Work time"))
        self.workTime_lbl.setText(_translate("mainWindow", "0"))
        self.label_5.setText(_translate("mainWindow", "Short break time"))
        self.shortBreakTime_lbl.setText(_translate("mainWindow", "0"))
        self.label_7.setText(_translate("mainWindow", "Long break time"))
        self.longBreakTime_lbl.setText(_translate("mainWindow", "0"))
        self.groupBox1.setTitle(_translate("mainWindow", "Short breaks"))
        self.label_11.setText(_translate("mainWindow", "Number of short breaks"))
        self.numberOfShortBreak_lbl.setText(_translate("mainWindow", "0"))
        self.label_9.setText(_translate("mainWindow", "Number of short breaks at the computer"))
        self.numberOfShortBreakComp_lbl.setText(_translate("mainWindow", "0"))
        self.label_13.setText(_translate("mainWindow", "Number of postponed short breaks"))
        self.numberOfPostponedShortBreaks_lbl.setText(_translate("mainWindow", "0"))
        self.label_15.setText(_translate("mainWindow", "Number of skipped short breaks"))
        self.numberOfSkippededShortBreaks_lbl.setText(_translate("mainWindow", "0"))
        self.groupBox_2.setTitle(_translate("mainWindow", "Long breaks"))
        self.label_19.setText(_translate("mainWindow", "Number of long breaks"))
        self.numberOfLongBreak_lbl.setText(_translate("mainWindow", "0"))
        self.label_17.setText(_translate("mainWindow", "Number of long breaks at the computer"))
        self.numberOfLongBreakComp_lbl.setText(_translate("mainWindow", "0"))
        self.label_21.setText(_translate("mainWindow", "Number of postponed long breaks"))
        self.numberOfPostponedLongBreaks_lbl.setText(_translate("mainWindow", "0"))
        self.label_23.setText(_translate("mainWindow", "Number of skipped long breaks"))
        self.numberOfSkippededLongBreaks_lbl.setText(_translate("mainWindow", "0"))
        self.reset_pushButton.setText(_translate("mainWindow", "Reset"))
        self.close_pushButton.setText(_translate("mainWindow", "Close"))

